context:
  version: "2.30.7"

package:
  name: ember-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@ember-tooling/ember-language-server/-/ember-language-server-${{ version }}.tgz
  sha256: 0ef1476865cc10b53022e96dcd7684c60ebae74fb882c397dd850d1a434c291f

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ember-language-server --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Language Server Protocol implementation for Ember.js projects
  homepage: https://github.com/ember-tooling/ember-language-server
  repository: https://github.com/ember-tooling/ember-language-server

extra:
  recipe-maintainers:
    - danielnachun
